export const BIBLE_BOOKS = [
  { abbrev: 'Gn', name: 'Gênesis', chapters: 50 },
  { abbrev: 'Êx', name: 'Êxodo', chapters: 40 },
  { abbrev: 'Lv', name: 'Levítico', chapters: 27 },
  { abbrev: 'Nm', name: 'Números', chapters: 36 },
  { abbrev: 'Dt', name: 'Deuteronômio', chapters: 34 },
  { abbrev: 'Js', name: 'Josué', chapters: 24 },
  { abbrev: 'Jz', name: 'Juízes', chapters: 21 },
  { abbrev: 'Rt', name: 'Rute', chapters: 4 },
  { abbrev: '1Sm', name: '1 Samuel', chapters: 31 },
  { abbrev: '2Sm', name: '2 Samuel', chapters: 24 },
  { abbrev: '1Rs', name: '1 Reis', chapters: 22 },
  { abbrev: '2Rs', name: '2 Reis', chapters: 25 },
  { abbrev: '1Cr', name: '1 Crônicas', chapters: 29 },
  { abbrev: '2Cr', name: '2 Crônicas', chapters: 36 },
  { abbrev: 'Ed', name: 'Esdras', chapters: 10 },
  { abbrev: 'Ne', name: 'Neemias', chapters: 13 },
  { abbrev: 'Et', name: 'Ester', chapters: 10 },
  { abbrev: 'Jó', name: 'Jó', chapters: 42 },
  { abbrev: 'Sl', name: 'Salmos', chapters: 150 },
  { abbrev: 'Pv', name: 'Provérbios', chapters: 31 },
  { abbrev: 'Ec', name: 'Eclesiastes', chapters: 12 },
  { abbrev: 'Ct', name: 'Cânticos', chapters: 8 },
  { abbrev: 'Is', name: 'Isaías', chapters: 66 },
  { abbrev: 'Jr', name: 'Jeremias', chapters: 52 },
  { abbrev: 'Lm', name: 'Lamentações', chapters: 5 },
  { abbrev: 'Ez', name: 'Ezequiel', chapters: 48 },
  { abbrev: 'Dn', name: 'Daniel', chapters: 12 },
  { abbrev: 'Os', name: 'Oséias', chapters: 14 },
  { abbrev: 'Jl', name: 'Joel', chapters: 3 },
  { abbrev: 'Am', name: 'Amós', chapters: 9 },
  { abbrev: 'Ob', name: 'Obadias', chapters: 1 },
  { abbrev: 'Jn', name: 'Jonas', chapters: 4 },
  { abbrev: 'Mq', name: 'Miquéias', chapters: 7 },
  { abbrev: 'Na', name: 'Naum', chapters: 3 },
  { abbrev: 'Hc', name: 'Habacuque', chapters: 3 },
  { abbrev: 'Sf', name: 'Sofonias', chapters: 3 },
  { abbrev: 'Ag', name: 'Ageu', chapters: 2 },
  { abbrev: 'Zc', name: 'Zacarias', chapters: 14 },
  { abbrev: 'Ml', name: 'Malaquias', chapters: 4 },
  { abbrev: 'Mt', name: 'Mateus', chapters: 28 },
  { abbrev: 'Mc', name: 'Marcos', chapters: 16 },
  { abbrev: 'Lc', name: 'Lucas', chapters: 24 },
  { abbrev: 'Jo', name: 'João', chapters: 21 },
  { abbrev: 'At', name: 'Atos', chapters: 28 },
  { abbrev: 'Rm', name: 'Romanos', chapters: 16 },
  { abbrev: '1Co', name: '1 Coríntios', chapters: 16 },
  { abbrev: '2Co', name: '2 Coríntios', chapters: 13 },
  { abbrev: 'Gl', name: 'Gálatas', chapters: 6 },
  { abbrev: 'Ef', name: 'Efésios', chapters: 6 },
  { abbrev: 'Fp', name: 'Filipenses', chapters: 4 },
  { abbrev: 'Cl', name: 'Colossenses', chapters: 4 },
  { abbrev: '1Ts', name: '1 Tessalonicenses', chapters: 5 },
  { abbrev: '2Ts', name: '2 Tessalonicenses', chapters: 3 },
  { abbrev: '1Tn', name: '1 Timóteo', chapters: 6 },
  { abbrev: '2Tm', name: '2 Timóteo', chapters: 4 },
  { abbrev: 'Tt', name: 'Tito', chapters: 3 },
  { abbrev: 'Fm', name: 'Filemom', chapters: 1 },
  { abbrev: 'Hb', name: 'Hebreus', chapters: 13 },
  { abbrev: 'Tg', name: 'Tiago', chapters: 5 },
  { abbrev: '1Pe', name: '1 Pedro', chapters: 5 },
  { abbrev: '2Pe', name: '2 Pedro', chapters: 3 },
  { abbrev: '1Jo', name: '1 João', chapters: 5 },
  { abbrev: '2Jo', name: '2 João', chapters: 1 },
  { abbrev: '3Jo', name: '3 João', chapters: 1 },
  { abbrev: 'Jd', name: 'Judas', chapters: 1 },
  { abbrev: 'Ap', name: 'Apocalipse', chapters: 22 },
];

export type BibleVersion = 'ARA' | 'NVI' | 'NAA';

export const BIBLE_VERSIONS: { key: BibleVersion; label: string; description: string }[] = [
  { key: 'ARA', label: 'ARA', description: 'Almeida Revista e Atualizada' },
  { key: 'NVI', label: 'NVI', description: 'Nova Versão Internacional' },
  { key: 'NAA', label: 'NAA', description: 'Nova Almeida Atualizada' },
];
